[package]
name = "introduction_to_yewrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
stylist = { version = "0.10.0", features = ["yew"]}
gloo = "0.8.0"
wasm-bindgen = "0.2.79"
web-sys = { version = "0.3.56", features = ["HtmlInputElement"] }
yew-router = "0.16.0"
yewdux = "0.8.2"
yewdux-functional = "0.1.0"
serde = "1.0.136"
reqwasm = "0.5.0"
bounce = "0.3.0"
wasm-bindgen-futures = "0.4.29"
serde_json = "1.0.79"